### ISSUE TITLE
To the sub-pages, add the "in XYZ resource"

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-planning-and-managing#13]
like in https://www.w3.org/WAI/media/av/planning/
and https://www.w3.org/WAI/people-use-web/user-stories/

**Comment by remibetin** [comment]
@shawna-slh Done by https://github.com/w3c/wai-website/commit/8dfe56962afa8146b13179c502404367dbc91a71! 

See for example https://www.w3.org/WAI/planning-and-managing/initiate/
